const chatData: { [key: string]: string } = {
    "hi": "Hi there! How can I assist you with AI-Solution today?",
    "hello": "Hi there! How can I assist you with AI-Solution today?",
    "what is ai-solution?": "AI-Solution is a cutting-edge platform designed to provide AI-powered solutions for businesses and individuals.",
    "features of ai-solution": "AI-Solution offers features like data analysis, predictive modeling, chatbot integration, and AI-powered insights tailored to your needs.",
    "how can ai-solution help me?": "AI-Solution can streamline your business operations, provide valuable insights, and automate repetitive tasks to save time and resources.",
    "pricing of ai-solution": "Our pricing depends on the plan you choose. Please visit the pricing section of our website or contact us for detailed information.",
    "support options": "We offer 24/7 customer support via email, chat, and phone to assist you with any issues or questions.",
    "integrations available": "AI-Solution integrates seamlessly with popular platforms like Google Workspace, Microsoft Office, and many CRM tools.",
    "use cases": "AI-Solution is ideal for e-commerce, healthcare, finance, education, and many other industries seeking AI-driven improvements.",
    "data privacy": "We prioritize your data privacy and comply with all major regulations, including GDPR and CCPA.",
    "how to get started?": "To get started, sign up on our website and choose the plan that best suits your needs. Our onboarding process is quick and easy!",
    "customization options": "AI-Solution offers extensive customization to tailor the platform to your unique requirements.",
    "contact information": "You can reach us at support@ai-solution.com or call us at +123-456-7890 for further assistance.",
    "bye": "Goodbye! Feel free to return if you have more questions about AI-Solution.",
    "thank you": "You're welcome! Let me know if there's anything else I can help with.",
    "help": "I'm here to answer your questions about AI-Solution. What would you like to know?",
    "tell me more about ai-solution": "AI-Solution combines advanced AI technologies to help you achieve your goals efficiently and effectively.",
    "what can you do?": "I can assist with information about AI-Solution, answer your questions, and guide you through its features.",
    "who made you?": "I was developed as part of the AI-Solution platform to assist users like you.",
    "what's your name?": "I'm the AI-Solution Chatbot, your virtual assistant!",
    "how are you?": "I'm just a bot, but I'm here to help you!",
    "where are you located?": "I live in the digital world, right here in the AI-Solution system.",
    "tell me a joke": "Why don't scientists trust atoms? Because they make up everything!",
    "do you like ai-solution?": "Of course! AI-Solution is an amazing platform that helps people achieve their goals with AI.",
    "who are your creators?": "AI-Solution was developed by a talented team of engineers and AI specialists.",
    "can i try ai-solution for free?": "Yes, we offer a free trial. Please visit our website to learn more and get started.",
    "what industries does ai-solution support?": "AI-Solution supports various industries like healthcare, finance, education, and more.",
    "what makes ai-solution unique?": "Our platform is designed to be user-friendly, highly customizable, and packed with cutting-edge AI features.",
    "can you help me decide a plan?": "Absolutely! Let me know your requirements, and I’ll guide you to the best plan for your needs.",
    "is ai-solution secure?": "Yes, we follow stringent security protocols and comply with major data privacy regulations.",
    "goodbye": "Goodbye! Take care and come back anytime for assistance.",
    "Who are you?": "I am the Ai-Solution Chatbpt, your virtual assistant!",

    // Additional common data
    "how do I reset my password?": "To reset your password, click on 'Forgot Password' on the login page and follow the instructions sent to your email.",
    "how do I contact support?": "You can contact support via email at support@ai-solution.com or use the live chat on our website.",
    "is there a mobile app?": "Currently, AI-Solution is accessible via web browser. Stay tuned for updates about our mobile app.",
    "can I cancel my subscription?": "Yes, you can cancel your subscription anytime from your account settings.",
    "how do I update my profile?": "Log in to your account, go to 'Profile Settings', and make the necessary changes.",
    "do you offer training?": "Yes, we provide onboarding and training resources. Contact our support team for more details.",
    "what payment methods do you accept?": "We accept major credit cards, PayPal, and bank transfers.",
    "how do I delete my account?": "To delete your account, please contact our support team for assistance.",
    "can I change my plan later?": "Absolutely! You can upgrade or downgrade your plan anytime from your account dashboard.",
    "is my data backed up?": "Yes, we regularly back up your data to ensure its safety and integrity.",
    "do you offer API access?": "Yes, API access is available for certain plans. Please check our documentation or contact support for more information.",
    "how do I invite team members?": "Go to your dashboard, select 'Team Management', and invite members by entering their email addresses.",
    "do you have a refund policy?": "Yes, we offer a refund policy. Please refer to our terms and conditions or contact support for details.",
    "can I get a demo?": "Yes, you can request a demo by filling out the form on our website or contacting our sales team.",
    "what languages are supported?": "Currently, AI-Solution supports English. More languages will be added soon.",
    "how do I report a bug?": "Please report bugs via our support email or the feedback form in your dashboard.",
    "is there a user guide?": "Yes, you can find the user guide in the 'Help' section of our website.",
    "how do I change my email address?": "Go to 'Profile Settings' and update your email address. You may need to verify the new email.",
    "can I export my data?": "Yes, you can export your data from the 'Data Management' section in your account.",
    "do you offer discounts for students or non-profits?": "We offer special discounts for students and non-profits. Please contact our sales team for eligibility and details."
};

export default chatData;